name: publish

on:
  push:
    branches: ['master']
    paths:
    - Containerfile
    - 'src/**'
    - '**.yml'

  release:
    types:
    - released

env:
  REG: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: login-registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: meta-gen
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REG }}/${{ github.repository }}

      - name: build-push
        id: push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:   ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: attest-artifacts
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REG }}/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
